#!/usr/bin/env bash
# Shared model aliases, limits, and Task Pack budgets.

agent_model_preset_load() {
  [[ "$#" -eq 1 ]] || return 2

  local model="$1"
  local model_key
  model_key="$(printf '%s' "$model" | tr '[:upper:]' '[:lower:]' | tr ' _' '--')"

  AGENT_RAILS_MODEL_KNOWN=0
  AGENT_RAILS_MODEL_PRESET_FOUND=0
  AGENT_RAILS_MODEL_CANONICAL="$model"
  AGENT_RAILS_MODEL_CONTEXT_TOKENS=""
  AGENT_RAILS_MODEL_MAX_INPUT_TOKENS=""
  AGENT_RAILS_MODEL_MAX_INPUT_THINKING_TOKENS=""
  AGENT_RAILS_MODEL_MAX_OUTPUT_TOKENS=""
  AGENT_RAILS_MODEL_MAX_REASONING_TOKENS=""
  AGENT_RAILS_MODEL_RPM=""
  AGENT_RAILS_MODEL_TPM=""
  AGENT_RAILS_MODEL_LITE_TOKENS=""
  AGENT_RAILS_MODEL_NORMAL_TOKENS=""
  AGENT_RAILS_MODEL_DEEP_TOKENS=""
  AGENT_RAILS_MODEL_AUDIT_TOKENS=""

  case "$model_key" in
    generic)
      AGENT_RAILS_MODEL_KNOWN=1
      ;;
    qwen3.7-max|qwen-3.7-max|qwen3.7max)
      AGENT_RAILS_MODEL_KNOWN=1
      AGENT_RAILS_MODEL_PRESET_FOUND=1
      AGENT_RAILS_MODEL_CANONICAL="qwen3.7-max"
      AGENT_RAILS_MODEL_CONTEXT_TOKENS=1000000
      AGENT_RAILS_MODEL_MAX_INPUT_TOKENS=991000
      AGENT_RAILS_MODEL_MAX_INPUT_THINKING_TOKENS=983000
      AGENT_RAILS_MODEL_MAX_OUTPUT_TOKENS=64000
      AGENT_RAILS_MODEL_MAX_REASONING_TOKENS=256000
      AGENT_RAILS_MODEL_LITE_TOKENS=24000
      AGENT_RAILS_MODEL_NORMAL_TOKENS=60000
      AGENT_RAILS_MODEL_DEEP_TOKENS=160000
      AGENT_RAILS_MODEL_AUDIT_TOKENS=320000
      ;;
    deepseek-v4-pro|deepseekv4pro|deepseek-v4pro|deepseek-v4|deepseek4-pro)
      AGENT_RAILS_MODEL_KNOWN=1
      AGENT_RAILS_MODEL_PRESET_FOUND=1
      AGENT_RAILS_MODEL_CANONICAL="deepseek-v4-pro"
      AGENT_RAILS_MODEL_CONTEXT_TOKENS=1000000
      AGENT_RAILS_MODEL_MAX_INPUT_TOKENS=1000000
      AGENT_RAILS_MODEL_MAX_OUTPUT_TOKENS=384000
      AGENT_RAILS_MODEL_RPM=15000
      AGENT_RAILS_MODEL_TPM=1200000
      AGENT_RAILS_MODEL_LITE_TOKENS=24000
      AGENT_RAILS_MODEL_NORMAL_TOKENS=60000
      AGENT_RAILS_MODEL_DEEP_TOKENS=160000
      AGENT_RAILS_MODEL_AUDIT_TOKENS=320000
      ;;
    glm5.1|glm-5.1|glm51)
      AGENT_RAILS_MODEL_KNOWN=1
      AGENT_RAILS_MODEL_PRESET_FOUND=1
      AGENT_RAILS_MODEL_CANONICAL="glm5.1"
      AGENT_RAILS_MODEL_CONTEXT_TOKENS=202000
      AGENT_RAILS_MODEL_MAX_INPUT_TOKENS=202000
      AGENT_RAILS_MODEL_MAX_INPUT_THINKING_TOKENS=166000
      AGENT_RAILS_MODEL_MAX_OUTPUT_TOKENS=128000
      AGENT_RAILS_MODEL_LITE_TOKENS=12000
      AGENT_RAILS_MODEL_NORMAL_TOKENS=24000
      AGENT_RAILS_MODEL_DEEP_TOKENS=60000
      AGENT_RAILS_MODEL_AUDIT_TOKENS=100000
      ;;
  esac
}

agent_model_preset_known() {
  [[ "$#" -eq 1 ]] || return 2
  agent_model_preset_load "$1"
  [[ "$AGENT_RAILS_MODEL_KNOWN" -eq 1 ]]
}

agent_model_preset_budget_for_mode() {
  [[ "$#" -eq 1 ]] || return 2

  case "$1" in
    lite) printf '%s\n' "${AGENT_RAILS_MODEL_LITE_TOKENS:-}" ;;
    normal) printf '%s\n' "${AGENT_RAILS_MODEL_NORMAL_TOKENS:-}" ;;
    deep) printf '%s\n' "${AGENT_RAILS_MODEL_DEEP_TOKENS:-}" ;;
    audit) printf '%s\n' "${AGENT_RAILS_MODEL_AUDIT_TOKENS:-}" ;;
  esac
}
