"""Render and atomically publish the final Agent Rails Task Pack."""

from __future__ import annotations

from dataclasses import dataclass
import html
from pathlib import Path
import re
from typing import Any, Mapping, Optional, Tuple

from agent_rails.context.assembler import SECTION_RULES, assemble, split_sections
from agent_rails.context.markdown import (
    display_text,
    has_markdown_heading,
    markdown_code,
    markdown_fence,
)
from agent_rails.context.pack_policy import PackPolicy
from agent_rails.core.private_text import (
    PrivateTextArtifact,
    PrivateTextNonRegularError,
    PrivateTextPublishError,
    publish_private_text_batch,
)
from agent_rails.models.tokenizer import TokenCounter


__all__ = (
    "PackRendererError",
    "RenderedPackSections",
    "TaskPackRenderRequest",
    "TaskPackRenderResult",
    "TokenizerSettings",
    "build_task_pack",
    "render_task_pack",
    "write_task_pack",
)


_UNSAFE_SINGLE_LINE_GOAL = re.compile(
    r"(?: {4}|\t| {0,3}(?:#{1,6}(?:[ \t]|$)|`{3,}|~{3,}|[>+*_-]|"
    r"[0-9]{1,9}[.)](?:[ \t]|$)|\[[^\]]+\]:))"
)
_TRUNCATION_MARKER = "\n...[truncated by Agent Rails budget]...\n"


class PackRendererError(RuntimeError):
    """The final Task Pack could not be rendered or published safely."""


@dataclass(frozen=True)
class RenderedPackSections:
    """Trusted, already-rendered sections in their semantic Pack slots."""

    git_evidence: str
    project_docs_entry: str
    agent_contract: str
    subagent_contract: str
    project_configuration: str
    memory_evidence: str
    verification_suggestions: str
    delivery_checklist: str


@dataclass(frozen=True)
class TokenizerSettings:
    """Replaceable Tokenizer Interface settings for an optional hard cap."""

    mode: str = "auto"
    command: str = ""
    path: str = ""
    tiktoken_encoding: str = "cl100k_base"
    working_directory: Optional[Path] = None
    environment: Optional[Mapping[str, str]] = None


@dataclass(frozen=True)
class TaskPackRenderRequest:
    """Inputs resolved by Pack Policy and the upstream context Modules."""

    goal: str
    display_path: str
    policy: PackPolicy
    sections: RenderedPackSections
    tokenizer: TokenizerSettings = TokenizerSettings()


@dataclass(frozen=True)
class TaskPackRenderResult:
    content: str
    assembler_metadata: Optional[Mapping[str, Any]]


def render_task_pack(request: TaskPackRenderRequest) -> str:
    """Render the full uncapped Pack in the historical stable section order."""

    _require_text(request.goal, "goal")
    _require_text(request.display_path, "display path")
    section_values = _section_values(request.sections)
    verification = _render_verification(
        request.sections.verification_suggestions,
        request.policy.budget.verify_chars,
    )
    content = "".join(
        (
            "# Agent Task Pack\n\n",
            "> Generated by Agent Rails.\n\n",
            _render_session_marker(request),
            _render_goal(request.goal),
            _render_context_budget(request.policy, request.tokenizer),
            section_values[0],
            section_values[1],
            section_values[2],
            section_values[3],
            section_values[4],
            section_values[5],
            verification,
            section_values[7],
        )
    )
    _strict_utf8(content)
    _validate_structure(content, hard_token_budget=None)
    return content


def build_task_pack(request: TaskPackRenderRequest) -> TaskPackRenderResult:
    """Render a Pack and optionally enforce the resolved hard token cap."""

    raw = render_task_pack(request)
    budget = request.policy.budget
    if budget.candidate_output_active or not budget.token_allocator_active:
        return TaskPackRenderResult(content=raw, assembler_metadata=None)
    if budget.effective_tokens is None or budget.effective_tokens <= 0:
        raise PackRendererError(
            "Task Pack hard token allocation requires a positive token budget."
        )

    settings = request.tokenizer
    try:
        counter = TokenCounter(
            settings.mode,
            budget.chars_per_token,
            settings.command,
            settings.path,
            settings.tiktoken_encoding,
            settings.working_directory,
            settings.environment,
        )
        content, metadata = assemble(raw, budget.effective_tokens, counter)
        _strict_utf8(content)
    except (OSError, UnicodeError, ValueError, RuntimeError) as exc:
        raise PackRendererError(
            f"Unable to enforce Task Pack token budget "
            f"{budget.effective_tokens}: {exc}"
        ) from exc
    _validate_structure(content, hard_token_budget=budget.effective_tokens)
    return TaskPackRenderResult(content=content, assembler_metadata=metadata)


def write_task_pack(
    output_path: Path, request: TaskPackRenderRequest
) -> TaskPackRenderResult:
    """Publish through a mode-0600 sibling staging file and atomic replace."""

    output_path = Path(output_path)
    result = build_task_pack(request)
    try:
        publish_private_text_batch(
            (
                PrivateTextArtifact(
                    key="task-pack",
                    target=output_path,
                    content=result.content,
                    staging_prefix=".agent-rails-task-pack.",
                ),
            )
        )
    except PrivateTextNonRegularError as exc:
        raise PackRendererError(
            f"Task Pack output is not a regular file: {output_path}"
        ) from exc
    except PrivateTextPublishError as exc:
        raise PackRendererError(
            f"Unable to replace Task Pack output: {output_path}"
        ) from exc
    return result


def _render_session_marker(request: TaskPackRenderRequest) -> str:
    display_path = markdown_code(request.display_path)
    return (
        "## Session Marker\n\n"
        f"AGENT RAILS: ON (mode={request.policy.density.mode}, "
        f"pack={display_path})\n\n"
        "- Relay the marker above before continuing; if intentionally skipped "
        "later, say `AGENT RAILS: SKIPPED (reason=<reason>)`.\n\n"
    )


def _render_goal(goal: str) -> str:
    normalized = (
        goal.replace("\r\n", "\n")
        .replace("\r", "\n")
        .replace("\x85", "\n")
        .replace("\u2028", "\n")
        .replace("\u2029", "\n")
    )
    lines = normalized.split("\n")
    display_lines = tuple(display_text(line) for line in lines)
    escaped_lines = tuple(
        html.escape(line, quote=False) for line in display_lines
    )
    unsafe = len(lines) > 1 or bool(
        _UNSAFE_SINGLE_LINE_GOAL.match(display_lines[0])
    )
    if unsafe:
        rendered = "\n".join(f"> {line}" for line in escaped_lines)
    else:
        rendered = escaped_lines[0]
    return f"## Goal\n\n{rendered}\n\n"


def _render_context_budget(
    policy: PackPolicy, tokenizer: TokenizerSettings
) -> str:
    model = policy.model
    preset = model.preset
    density = policy.density
    budget = policy.budget
    lines = ["## Context Budget\n\n", f"- Model: {markdown_code(model.canonical)}"]
    if preset is None:
        lines.append(" (no preset)")
    else:
        lines.append(
            f" (context `{preset.context_tokens}` tokens, "
            f"max input `{preset.max_input_tokens}` tokens"
        )
        if preset.max_input_thinking_tokens is not None:
            lines.append(
                f", thinking input `{preset.max_input_thinking_tokens}` tokens"
            )
        lines.append(f", max output `{preset.max_output_tokens}` tokens")
        if preset.max_reasoning_tokens is not None:
            lines.append(f", max reasoning `{preset.max_reasoning_tokens}` tokens")
        if preset.rpm is not None:
            lines.append(f", rpm `{preset.rpm}`")
        if preset.tpm is not None:
            lines.append(f", tpm `{preset.tpm}`")
        lines.append(")")
    lines.extend(
        [
            "\n",
            f"- Pack mode: `{density.mode}`\n",
        ]
    )
    if density.mode == "lite":
        lines.append(
            "- Lite mode: skip full grill, keep context/checklist/memory/"
            "verification focused, and ask only blocker questions.\n"
        )
    lines.extend(
        [
            f"- Grill question budget: `{density.grill_max_questions}`\n",
            f"- Chars/token estimate: `{budget.chars_per_token}`\n",
        ]
    )

    if budget.candidate_output_active:
        lines.append(
            "- Mode: candidate output; the request hook applies the live hard "
            "token budget.\n"
        )
    elif budget.token_allocator_active:
        lines.extend(
            [
                "- Mode: hard token budget with weighted allocation and "
                "unused-share redistribution.\n",
                f"- Budget source: {markdown_code(budget.source)}\n",
                f"- Token budget: `{budget.effective_tokens}` tokens\n",
                f"- Total: `{budget.total_chars}` chars (candidate estimate "
                "before hard token allocation)\n",
                f"- Requested tokenizer: {markdown_code(tokenizer.mode)}\n",
                "- Allocation weights: mandatory `10%`, git `35%`, contract "
                "`25%`, memory `15%`, verification `15%`.\n",
                "- Empty or satisfied categories return unused tokens to "
                "categories with remaining demand.\n",
            ]
        )
    elif budget.total_chars > 0:
        lines.extend(
            [
                "- Mode: bounded by approximate character budget.\n",
                f"- Budget source: {markdown_code(budget.source)}\n",
            ]
        )
        if budget.effective_tokens is not None:
            lines.append(
                f"- Token budget: `{budget.effective_tokens}` tokens\n"
            )
        lines.extend(
            [
                f"- Total: `{budget.total_chars}` chars\n",
                f"- Git state: `{budget.git_percent}%` -> "
                f"`{budget.git_chars}` chars\n",
                f"  - Changed file sort: {markdown_code(density.changed_file_sort)}\n",
                f"  - Changed files: `{budget.changed_files_chars}` chars\n",
                f"  - Working tree status: `{budget.status_chars}` chars\n",
                f"  - Changed file excerpts: `{density.changed_file_excerpt_limit}` "
                f"file(s), `{density.changed_file_excerpt_chars}` chars each\n",
                f"- Memory cards: `{budget.memory_percent}%` -> "
                f"`{budget.memory_chars}` chars\n",
                f"- Verification suggestions: `{budget.verify_percent}%` -> "
                f"`{budget.verify_chars}` chars\n",
                f"- Contract/checklist: `{budget.contract_percent}%` -> "
                f"`{budget.contract_chars}` chars\n",
            ]
        )
    else:
        lines.extend(
            [
                "- Global budget: none; Pack Mode density caps still apply. Set "
                "`--model NAME`, `--budget CHARS`, or `--token-budget TOKENS` "
                "for section budgets.\n",
                f"- Local memory card cap: "
                f"`{density.local_memory_card_chars}` chars per card.\n",
                f"- Changed file sort: "
                f"{markdown_code(density.changed_file_sort)}.\n",
                f"- Changed file excerpts: "
                f"`{density.changed_file_excerpt_limit}` file(s), "
                f"`{density.changed_file_excerpt_chars}` chars each.\n",
            ]
        )
    lines.append("\n")
    return "".join(lines)


def _render_verification(suggestions: str, budget: int) -> str:
    _require_text(suggestions, "verification suggestions")
    body = _complete_lines(suggestions, budget)
    if body and not body.endswith(("\n", "\r")):
        body += "\n"
    fence = markdown_fence(body, "`", 3)
    return (
        "## Verification Suggestions\n\n"
        f"{fence}text\n"
        f"{body}"
        f"{fence}\n\n"
    )


def _complete_lines(text: str, budget: int) -> str:
    if budget <= 0:
        return text
    rendered = []
    used = 0
    truncated = False
    for line in text.splitlines(keepends=True):
        if used + len(line) > budget:
            truncated = True
            break
        rendered.append(line)
        used += len(line)
    if truncated:
        rendered.append(_TRUNCATION_MARKER)
    return "".join(rendered)


def _section_values(sections: RenderedPackSections) -> Tuple[str, ...]:
    values = (
        sections.git_evidence,
        sections.project_docs_entry,
        sections.agent_contract,
        sections.subagent_contract,
        sections.project_configuration,
        sections.memory_evidence,
        sections.verification_suggestions,
        sections.delivery_checklist,
    )
    names = (
        "git evidence",
        "project docs entry",
        "agent contract",
        "subagent contract",
        "project configuration",
        "memory evidence",
        "verification suggestions",
        "delivery checklist",
    )
    for name, value in zip(names, values):
        _require_text(value, name)
    return values


def _require_text(value: object, name: str) -> None:
    if not isinstance(value, str):
        raise PackRendererError(f"Task Pack {name} must be text.")


def _strict_utf8(value: str) -> bytes:
    try:
        return value.encode("utf-8", errors="strict")
    except UnicodeError as exc:
        raise PackRendererError(
            "Task Pack content is not valid strict UTF-8."
        ) from exc


def _validate_structure(
    content: str, *, hard_token_budget: Optional[int]
) -> None:
    sections = split_sections(content)
    names = tuple(
        section.name for section in sections if section.name != "__preamble__"
    )
    required = tuple(SECTION_RULES)
    agent_contract = next(
        (
            section.text
            for section in sections
            if section.name == "Agent Rails Contract"
        ),
        "",
    )
    valid = (
        content.startswith("# Agent Task Pack\n\n> Generated by Agent Rails.\n\n")
        and names == required
        and has_markdown_heading(agent_contract, 3, "Grill Gate")
    )
    if valid:
        return
    if hard_token_budget is None:
        raise PackRendererError(
            "Task Pack renderer did not preserve required section structure."
        )
    raise PackRendererError(
        f"Task Pack token budget {hard_token_budget} is too small to preserve "
        "all required sections and the Grill Gate."
    )
